# Generated by Django 4.1.3 on 2022-12-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('user_name', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('M', 'Mâle'), ('F', 'Femêlle'), ('O', 'Other')], max_length=1)),
                ('matricule_number', models.CharField(max_length=10)),
                ('classe', models.CharField(max_length=5)),
                ('pass_word_hashed', models.CharField(max_length=15)),
                ('contacte', models.CharField(max_length=25)),
                ('image_path', models.CharField(max_length=50)),
            ],
        ),
    ]
