# Generated by Django 4.1.3 on 2023-01-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_adminbibliotheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstudent', models.IntegerField()),
                ('link', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstudent', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('support_link', models.TextField(max_length=60)),
                ('link_net', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCompetences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstudent', models.IntegerField()),
                ('competence_title', models.CharField(max_length=50)),
                ('competences', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstudent', models.IntegerField()),
                ('ecole', models.CharField(max_length=20)),
                ('plusinfo', models.CharField(max_length=60)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentPrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstudent', models.IntegerField()),
                ('prix', models.CharField(max_length=20)),
                ('plusinfo', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstudent', models.IntegerField()),
                ('post', models.CharField(max_length=60)),
                ('niveau', models.CharField(max_length=60)),
                ('work', models.CharField(max_length=60)),
                ('about_me1', models.TextField()),
                ('about_me2', models.TextField()),
                ('photo_link', models.CharField(max_length=60)),
            ],
        ),
    ]
