# Generated by Django 4.1.3 on 2022-08-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6)),
                ('auteur', models.CharField(max_length=30)),
                ('titre', models.CharField(max_length=100)),
                ('edition', models.CharField(blank=True, max_length=10)),
                ('annee', models.IntegerField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=15)),
                ('cotation', models.CharField(max_length=10)),
                ('etat', models.IntegerField()),
                ('observation', models.CharField(blank=True, max_length=20)),
                ('categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhysiqueElectricite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6)),
                ('auteur', models.CharField(max_length=30)),
                ('titre', models.CharField(max_length=100)),
                ('edition', models.CharField(blank=True, max_length=10)),
                ('annee', models.IntegerField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=15)),
                ('cotation', models.CharField(max_length=10)),
                ('etat', models.IntegerField()),
                ('observation', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
