# Generated by Django 4.1.3 on 2023-01-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtopic', models.IntegerField()),
                ('idrepondeur', models.IntegerField()),
                ('reponse', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('idUser', models.IntegerField()),
                ('forum', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
