# Generated by Django 4.1.5 on 2023-01-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerAnswered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idoldreponse", models.IntegerField()),
                ("idrepondeur", models.IntegerField()),
                ("reponse", models.TextField()),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
