# Generated by Django 4.1.3 on 2022-08-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empruntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBook', models.IntegerField()),
                ('cotation', models.CharField(max_length=10)),
                ('titre', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('idUser', models.IntegerField()),
                ('dateSortie', models.DateTimeField()),
                ('dateEntre', models.DateTimeField()),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBook', models.IntegerField()),
                ('cotation', models.CharField(max_length=10)),
                ('titre', models.CharField(max_length=100)),
                ('categorie', models.CharField(max_length=50)),
                ('idUserEnAttent', models.IntegerField()),
                ('idUserEnCour', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
    ]
